package com.fivestars.websites.onlinetest.model;
// Generated Jan 15, 2016 12:20:03 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "article", catalog = "online_test")
public class Article implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer articleId;
	private String title;
	private String content;
	private Date createDate;
	private Integer category;
	private String submitter;

	public Article() {
	}
	
	public Article(Article article) {
		this.articleId = article.getArticleId();
		this.title = article.getTitle();
		this.content = article.getContent();
		this.createDate = article.getCreateDate();
		this.category = article.getCategory();
		this.submitter = article.getSubmitter();
	}

	public Article(String title, String content, Date createDate, Integer category, String submitter) {
		this.title = title;
		this.content = content;
		this.createDate = createDate;
		this.category = category;
		this.submitter = submitter;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "articleId", unique = true, nullable = false)
	public Integer getArticleId() {
		return this.articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "category")
	public Integer getCategory() {
		return this.category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	@Column(name = "submitter", length = 50)
	public String getSubmitter() {
		return this.submitter;
	}

	public void setSubmitter(String submitter) {
		this.submitter = submitter;
	}

}
