package com.fivestars.websites.onlinetest.model;
// Generated Jan 15, 2016 12:20:03 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "feedback", catalog = "online_test")
public class Feedback implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private Integer feedbackId;
	private Integer quizId;
	private String content;
	private Double scoreFrom;
	private Double scoreTo;

	public Feedback() {
	}

	public Feedback(int quizId) {
		this.quizId = quizId;
	}

	public Feedback(Integer quizId, String content, Double scoreFrom, Double scoreTo) {
		this.quizId = quizId;
		this.content = content;
		this.scoreFrom = scoreFrom;
		this.scoreTo = scoreTo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "feedbackId", unique = true, nullable = false)
	public Integer getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(Integer feedbackId) {
		this.feedbackId = feedbackId;
	}

	@Column(name = "quizId", nullable = false)
	public Integer getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Integer quizId) {
		this.quizId = quizId;
	}

	@Column(name = "content", columnDefinition="longtext")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "scoreFrom", precision = 22, scale = 0)
	public Double getScoreFrom() {
		return this.scoreFrom;
	}

	public void setScoreFrom(Double scoreFrom) {
		this.scoreFrom = scoreFrom;
	}

	@Column(name = "scoreTo", precision = 22, scale = 0)
	public Double getScoreTo() {
		return this.scoreTo;
	}

	public void setScoreTo(Double scoreTo) {
		this.scoreTo = scoreTo;
	}

}
