package com.fivestars.websites.onlinetest.model;
// Generated Jan 15, 2016 12:20:03 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QuizCategory generated by hbm2java
 */
@Entity
@Table(name = "quiz_category", catalog = "online_test")
public class QuizCategory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int categoryId;
	private String categoryName;
	private String description;
	private Integer parentId;

	public QuizCategory() {
	}

	public QuizCategory(int categoryId) {
		this.categoryId = categoryId;
	}

	public QuizCategory(int categoryId, String categoryName, String description, Integer parentId) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.description = description;
		this.parentId = parentId;
	}

	@Id

	@Column(name = "categoryId", unique = true, nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "categoryName", length = 50)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "parentId")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

}
