package com.fivestars.websites.onlinetest.model;
// Generated Jan 15, 2016 12:20:03 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubjectItem generated by hbm2java
 */
@Entity
@Table(name = "subject_item", catalog = "online_test")
public class SubjectItem implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer itemId;
	private QuizSubject quizSubject;
	private String option;
	private Double score;
	private Integer nextSubjectId;

	public SubjectItem() {
	}

	public SubjectItem(QuizSubject quizSubject) {
		this.quizSubject = quizSubject;
	}

	public SubjectItem(QuizSubject quizSubject, String option, Double score, Integer nextSubjectId) {
		this.quizSubject = quizSubject;
		this.option = option;
		this.score = score;
		this.nextSubjectId = nextSubjectId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "itemId", unique = true, nullable = false)
	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subjectId", nullable = false)
	public QuizSubject getQuizSubject() {
		return this.quizSubject;
	}

	public void setQuizSubject(QuizSubject quizSubject) {
		this.quizSubject = quizSubject;
	}

	@Column(name = "option", length = 65535)
	public String getOption() {
		return this.option;
	}

	public void setOption(String option) {
		this.option = option;
	}

	@Column(name = "score", precision = 22, scale = 0)
	public Double getScore() {
		return this.score;
	}

	public void setScore(Double score) {
		this.score = score;
	}

	@Column(name = "nextSubjectId")
	public Integer getNextSubjectId() {
		return this.nextSubjectId;
	}

	public void setNextSubjectId(Integer nextSubjectId) {
		this.nextSubjectId = nextSubjectId;
	}

}
