package com.fivestars.websites.onlinetest.model;
// Generated Jan 15, 2016 12:20:03 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserQuiz generated by hbm2java
 */
@Entity
@Table(name = "user_quiz", catalog = "online_test")
public class UserQuiz implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer recordId;
	private String userName;
	private int quizId;
	private Double score;
	private Integer feedbackId;
	private Date quizDate;
	private String evaluator;

	public UserQuiz() {
	}

	public UserQuiz(String userName, int quizId) {
		this.userName = userName;
		this.quizId = quizId;
	}

	public UserQuiz(String userName, int quizId, Double score, Integer feedbackId, Date quizDate, String evaluator) {
		this.userName = userName;
		this.quizId = quizId;
		this.score = score;
		this.feedbackId = feedbackId;
		this.quizDate = quizDate;
		this.evaluator = evaluator;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recordId", unique = true, nullable = false)
	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	@Column(name = "userName", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "quizId", nullable = false)
	public int getQuizId() {
		return this.quizId;
	}

	public void setQuizId(int quizId) {
		this.quizId = quizId;
	}

	@Column(name = "score", precision = 22, scale = 0)
	public Double getScore() {
		return this.score;
	}

	public void setScore(Double score) {
		this.score = score;
	}

	@Column(name = "feedbackId")
	public Integer getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(Integer feedbackId) {
		this.feedbackId = feedbackId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quizDate", length = 19)
	public Date getQuizDate() {
		return this.quizDate;
	}

	public void setQuizDate(Date quizDate) {
		this.quizDate = quizDate;
	}

	@Column(name = "evaluator", length = 50)
	public String getEvaluator() {
		return this.evaluator;
	}

	public void setEvaluator(String evaluator) {
		this.evaluator = evaluator;
	}

}
