package com.fivestars.websites.onlinetest.model;
// Generated Jan 15, 2016 12:20:03 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserAnswer generated by hbm2java
 */
@Entity
@Table(name = "user_answer", catalog = "online_test")
public class UserAnswer implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer answerId;
	private String userName;
	private Integer quizId;
	private Integer subjectId;
	private String answer;
	private Date answerDate;
	private Double score;
	private UserQuiz userQuiz;

	public UserAnswer() {
	}

	public UserAnswer(Integer subjectId) {
		this.subjectId = subjectId;
	}

	public UserAnswer(String userName, Integer quizId, int subjectId, String answer, Date answerDate, Double score) {
		this.userName = userName;
		this.quizId = quizId;
		this.subjectId = subjectId;
		this.answer = answer;
		this.answerDate = answerDate;
		this.score = score;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "answerId", unique = true, nullable = false)
	public Integer getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(Integer answerId) {
		this.answerId = answerId;
	}

	@Column(name = "userName", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "quizId")
	public Integer getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Integer quizId) {
		this.quizId = quizId;
	}

	@Column(name = "subjectId", nullable = false)
	public int getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "answer", length = 65535)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "answerDate", length = 19)
	public Date getAnswerDate() {
		return this.answerDate;
	}

	public void setAnswerDate(Date answerDate) {
		this.answerDate = answerDate;
	}

	@Column(name = "score", precision = 22, scale = 0)
	public Double getScore() {
		return this.score;
	}

	public void setScore(Double score) {
		this.score = score;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recordId", nullable = false)
	public UserQuiz getUserQuiz() {
		return userQuiz;
	}

	public void setUserQuiz(UserQuiz userQuiz) {
		this.userQuiz = userQuiz;
	}

}
